### ISSUE TITLE
uptime and response time undefined

### ISSUE THREAD

**Issue by revolunet** [upptime/upptime#126]
**Describe the bug**
Overall uptime and average response times appear "undefined"

Only the "All" filter display these numbers correctly

Example : https://socialgouv.github.io/upptime/

Thanks for upptime !

**Comment by AnandChowdhary** [comment]
This is `undefined` because you're not updated to the most recent version of Upptime, because your Update Template CI is not working: https://github.com/SocialGouv/upptime/actions?query=workflow%3A%22Update+Template+CI%22.

The workflow is not updated because your PAT does not have the `workflow` scope (https://github.com/SocialGouv/upptime/runs/1579793447?check_suite_focus=true). Please add it and then manually run Update Template CI to make everyone work!

**Comment by revolunet** [comment]
Thank you Anand
