### ISSUE TITLE
Telegram bot does not receive notification when website is down

### ISSUE THREAD

**Issue by hesingon** [upptime/upptime#156]
**Describe the bug**
Here is my [repository](https://github.com/hesingon/revisit_watcher), (version 1.23.13). I have setup telegram notification as per [documentation's instruction](https://upptime.js.org/docs/notifications): 

NOTIFICATION_TELEGRAM: `true`
NOTIFICATION_TELEGRAM_BOT_KEY : (something looks like this:) `123456:kioASDdjicOljd_ijsdf`
NOTIFICATION_TELEGRAM_CHAT_ID: (something looks like this:) `23141232`

Also I referred to this [StackOverflow answer](https://stackoverflow.com/questions/31197659/how-we-should-send-query-to-telegram-bot-api/31198286#31198286) and have ensured that the bot is working, I can use python's requests to send message to bot and can receive the message.

**To Reproduce**
With this setup, I modify test if telegram can work by doing the following:
1. add a new broken url in `.upptimerc.yml` under `sites`
2. commit and wait for `Update Template CI` and `Uptime CI` in Github Actions to complete.
3. Wait until a new issue is created because it detected the site is not up.

**Expected behavior**
I expect my telegram bot will send something to me. Nothing was sent

**Comment by alefvanoon** [comment]
telegram bot still  have problem!

**Comment by AnandChowdhary** [comment]
This is now (finally) fixed, thanks so much for your patience! The fix is available in [`upptime/uptime-monitor@v1.26.2`](https://github.com/upptime/uptime-monitor/releases/tag/v1.26.2), and the automated fix should be in your repositories within 24 hours.

You can also run Update Template CI [manually](https://upptime.js.org/docs/triggers) to update to the latest version immediately; by default this runs once every day.
