### ISSUE TITLE
It seems that the bot isn't updating the response time every 5 minutes

### ISSUE THREAD

**Issue by FxllenCode** [upptime/upptime#188]
Hi!

I've been working on an alternative to a public status site, but hooked up to the API instead of manually changing. However, it is _critical_ that the bot checks the response time every 5 minutes an update it, as the docs state:

![image](https://user-images.githubusercontent.com/40151425/103963120-83fdfd80-5126-11eb-8a06-ede5258a097b.png)

However, it seems that the bot is checking once per day, or on the `push` event:

![l6n1ArwdM9](https://user-images.githubusercontent.com/40151425/103963321-f53db080-5126-11eb-87e1-13fa4ef22b33.png)

Is this intended? If so, shouldn't the docs be updated/clarified? 

Thanks! 🙂 

EDIT:

Let me clarify; I understand that part is only commits once a day, but where can I find the response time being updated every 5 minutes? And why doesn't it update the response time on the site every 5 minutes?

**Comment by AnandChowdhary** [comment]
Yes, the currently expected behavior is that we check up/down status every 5 minutes, but response time only once per day. This is because to track response time, we need to commit to git history, and if we were doing this every 5 minutes, it would make your git history toooo large.

You can configure when this job runs by configuring the CI schedule: https://upptime.js.org/docs/configuration#ci-schedule. Currently, `responseTime` runs at `0 23 * * *`, i.e., at 00:23 am every day, and you can change it to run as frequently as you like.
