### ISSUE TITLE
uptime.json and response-time.json don't reflect the current status.

### ISSUE THREAD

**Issue by FxllenCode** [upptime/upptime#194]
**Describe the bug**
It seems that uptime.json and response-time.json under the api folder do not update when the status changes. Based on the name of these, they should change based on current information, not on information scaling a 24 hr range. (That would be uptime-day.json and response-time-day.json).

**To Reproduce**
1. Create an outage/degraded performance.
2. Go to api folder and choose uptime.json or response-time.json.
3. It doesn't show you current information, and shows you information that uptime-day.json contains.

**Expected behavior**
It's supposed to show the current status, i.e. response time on site shows 144ms, response time on response-time.json shows 144ms and shows the color as orange, not green. 

**Screenshots**
![chrome_Ryuw7FCmDl](https://user-images.githubusercontent.com/40151425/104112648-75971980-52bf-11eb-9abd-1ab3453d0dc1.png)

![OMpcZ7YMaO](https://user-images.githubusercontent.com/40151425/104112650-77f97380-52bf-11eb-8a76-a3c9d26869f8.png)

**Additional context**
It's possible this is intended, if so, where is an api that returns JSON with the current information? I cannot seem to find it anywhere.

**Comment by AnandChowdhary** [comment]
`uptime.json` and `response-time.json` don't show the latest, but the all-time values. Maybe I've named them in a confusing way, but the idea is `uptime-day.json` will give you the uptime for the day, `uptime-week.json` will for the week, and `uptime.json` will with the all-time average.

Therefore, this is expected behavior since the all-time average response time is 200ms, which is green. Maybe a feature request can be to have an `uptime-latest.json` which only shows the most recent value? If this will fix your use case, please open a Discussion with the idea! 😄
