### ISSUE TITLE
Page Build Warning

### ISSUE THREAD

**Issue by Lvl4Sword** [upptime/upptime#195]
**Describe the bug**
I have https://github.com/woodcoin-core/upptime being built to a Netlify subdomain - jolly-borg-0ef6f8.netlify.app
From that subdomain, I've got it tied to the status.woodcoin.org subdomain through an ANAME record.
I've gotten two e-mails stating the following:

> The page build completed successfully, but returned the following warning for the `gh-pages` branch:
>
> Your site's DNS settings are using a custom subdomain, jolly-borg-0ef6f8.netlify.app, that's set up as an A record. We recommend you change this to a CNAME record pointing at woodcoin-core.github.io. For more information, see https://docs.github.com/github/working-with-github-pages/configuring-a-custom-domain-for-your-github-pages-site.
>
>For information on troubleshooting Jekyll see:
>
>  https://docs.github.com/articles/troubleshooting-jekyll-builds
>
>If you have any questions you can submit a request on the Contact GitHub page at https://support.github.com/contact?repo_id=324907422&page_build_id=226101581

Is this not supported through upptime? How can I ( and possibly others ) suppress this?
There are no issues that I can see, and it looks like Github is complaining for no reason here.

**Expected behavior**
No e-mails from Github yelling at me.

**Comment by AnandChowdhary** [comment]
It looks like https://status.woodcoin.org is working perfectly through Netlify, so the issue is only the unnecessary email from GitHub.

This email is because of this line: https://github.com/woodcoin-core/upptime/blob/master/.upptimerc.yml#L17. You don't need to specify the custom `cname` domain when using Netlify. This is only a requirement for GitHub Pages.

What's happening now is that GitHub is trying to publish to the domain under `cname`, which is not mapped to GitHub Pages but to a different service, so they're asking you to use GitHub's CNAME. Removing the CNAME line will fix this issue.

**Comment by Lvl4Sword** [comment]
Appreciate the assistance!
