### ISSUE TITLE
Status always DOWN

### ISSUE THREAD

**Issue by williamdes** [upptime/upptime#268]
**Describe the bug**

The status is always DOWN

**To Reproduce**
https://github.com/wdes/status

**Expected behavior**
UP

**Screenshots**

https://github.com/wdes/status

**Comment by williamdes** [comment]
@AnandChowdhary I do not know why but my status is always DOWN but all the commits are always UP
https://github.com/wdes/status/commits/main

And the issue system works fine because when a service goes DOWN for real it does the work.
But on the website and on the summary it is always DOWN

**Comment by AnandChowdhary** [comment]
This is because you're using a custom commit message (https://github.com/wdes/status/blob/main/.upptimerc.yml#L60) using the variable `$EMOJI`. Instead, you should use the variable `$PREFIX` like we do. Because of this, none of your commits have the prefix emoji we use to detect whether a site is up or not.

If you are not using a custom commit message, it's best that you remove these lines and only keep the `commitAuthorName` and `commitAuthorEmail` values.

**Comment by williamdes** [comment]
Maybe it would be better to have the data in the commit body, that would avoid such issues.

But thank you, I will fix that
