### ISSUE TITLE
Status page breaks after refreshing the page without using the cache in Safari.

### ISSUE THREAD

**Issue by jtprog** [upptime/upptime#34]
- Safari version: `14.0 (15610.1.28.1.9, 15610)`
- My status page: [https://status.jtprog.ru](https://status.jtprog.ru/)
- My status repo: [https://github.com/jtprog/status.jtprog.ru](https://github.com/jtprog/status.jtprog.ru)

Steps:
1. Open status.jtprog.ru;
2. Press `Option+Cmd+E` for clear the cache;
3. Press `Cmd+R` for reload the page;

Result:
<a href="https://ibb.co/L8JRBs9"><img src="https://i.ibb.co/PN9jJV1/2020-10-20-00-00-27.png" alt="2020-10-20-00-00-27" border="0"></a>

Similar result on other site with `Upptime`.

UPD: Tested with and without external plugins for Safari.

UPD: Add this screenshot with JS Console:
<a href="https://ibb.co/dPYy1gt"><img src="https://i.ibb.co/Lx7fb5r/2020-10-20-00-23-40.png" alt="2020-10-20-00-23-40" border="0"></a>

**Comment by AnandChowdhary** [comment]
Thanks for opening this issue, @jtprog. You're right, I'm able to reproduce this in Safari. This is doubly weird because the `global.css` file clearly exists in the deployment: https://github.com/jtprog/status.jtprog.ru/blob/gh-pages/global.css.

I'm almost certain this has something to do with Sapper's service worker so I'll go ahead and update @upptime today after disabling it.

**Comment by AnandChowdhary** [comment]
Ok, so I've removed the service worker (your status website will be auto-updated within 24 hours with the new code!) and it works well in Safari now!
