### ISSUE TITLE
Uptime CI job fails with "Can't use 'tar -xzf' extract archive file" error

### ISSUE THREAD

**Issue by davidearthly** [upptime/upptime#623]
**Describe the bug**
Uptime CI job fails with "Can't use 'tar -xzf' extract archive file" error

**To Reproduce**
Unknown what the cause is - it seems to be an ephemeral issue as most runs pass.

Please see an example of this in Upptime's own repository: https://github.com/upptime/upptime/actions/runs/2747365664

This is happening occasionally in my own instance as well (private repository)

**Expected behavior**
The job not to fail

**Comment by thewilloftheshadow** [comment]
I'm also experiencing this issue

**Comment by fabiofdsantos** [comment]
Similar: https://github.com/actions/runner/issues/1923

**Comment by artemislena** [comment]
L: Got the same issue, but uh, what's interesting is it seems to be working sporadically, i.e. see https://github.com/artemislena/upptime/actions.

**Comment by Rileyjrjohns** [comment]
Same here

**Comment by harleykin** [comment]
I'm also experiencing this.

**Comment by SDS1337** [comment]
Also experiencing this

**Comment by Sam-Lin-MillersLab** [comment]
Let's use this thumb up buttons instead of replying something like "also experiencing this", so we don't keep spamming people who subscribes to this issue. 

<img width="105" alt="image" src="https://user-images.githubusercontent.com/27328563/181351734-0c33dc95-8c47-4b1a-8261-c26f20cb38bc.png">


I assume we are all programmers with enough intelligent to do something makes sense.

**Comment by fabiofdsantos** [comment]
It should be fixed now: https://github.com/actions/runner/issues/1923#issuecomment-1197341206

**Comment by AnandChowdhary** [comment]
Looks like we should be all green, thanks for the checkup everyone!
