### ISSUE TITLE
All sites are up, but they're all shown as down and there is "Complete outage"

### ISSUE THREAD

**Issue by Aeris1One** [upptime/upptime#703]
**Describe the bug**
All sites are up and detected as such by Actions, and the status page is "All sites are up" but all websites are shown as down on the same page, moreover the README show all website as down and "complete outage".
Uptime CI and Response Time CI are marking the websites as up in logs, but Summary CI shows `currentStatus: 'down'` in its logs. Graphs CI also isn't able to plot the response time.

**Additional context**
Repo is here : https://github.com/Altearn/status
Status page : https://status.altearn.xyz

**Comment by AnandChowdhary** [comment]
I'm not 100% sure, but I think it's because the commit message is contains "est up (200 en 1192 ms)" and because it's translated, Upptime doesn't recognize what it means. IIRC, we use the emoji in the beginning of the commit message to figure out if it's up or not; can you try removing the translation for the commit message and seeing what happens?

**Comment by Aeris1One** [comment]
Seems it fixed the issue, I followed the documentation about internationalisation, which doesn't include emojis on example strings.
Alright this is fixed ! Should I close it or would you like to use it as a tracker because such things shouldn't happen and the summary CI should take translations into account ?
