### ISSUE TITLE
Double percentage sign in alt text of generated README

### ISSUE THREAD

**Issue by aureooms** [upptime/upptime#83]
See for instance https://github.com/aureooms/monitor/blame/master/README.md#L19. It seems https://github.com/upptime/uptime-monitor/pull/45 would fix this error (I cannot comment there since the conversation is limited to collaborators). I originally thought https://github.com/upptime/uptime-monitor/pull/45 would fix the same kind of bug in the generated PWA, however I was wrong.

**Comment by aureooms** [comment]
Another solution would be to revert https://github.com/upptime/status-page/pull/64 and merge https://github.com/upptime/uptime-monitor/pull/44.

**Comment by AnandChowdhary** [comment]
I like the idea of having the formatted percentage (e.g., "92.34%") in the API, otherwise if we store the plain integers, I'd rather we store something like 0.9234 rather than 92.34. Then, the README/status website don't have to do any additional formatting and can use the response as-is. I think I'll just update the README alt text instead. Is that ok?

**Comment by aureooms** [comment]
> I like the idea of having the formatted percentage (e.g., "92.34%") in the API, otherwise if we store the plain integers, I'd rather we store something like 0.9234 rather than 92.34. Then, the README/status website don't have to do any additional formatting and can use the response as-is. I think I'll just update the README alt text instead. Is that ok?

Both `"92.34%"` and `0.9234` (not rounded?) make sense. The API could also contain both.
