### ISSUE TITLE
Live status 24h response time chart is always a flat line

### ISSUE THREAD

**Issue by SukkaW** [upptime/upptime#848]
**Describe the bug**

The live status 24-hour response time chart is always a flat line

**To Reproduce**

- Go to https://demo.upptime.js.org/
- Click `24h` right after `Live Status`
  <img width="775" alt="image" src="https://github.com/upptime/upptime/assets/40715044/eab1a8b7-e619-40a8-b456-5873c9ca2340">
- Response time shows a flat line:
  <img width="779" alt="image" src="https://github.com/upptime/upptime/assets/40715044/b60c1ee3-54d0-4158-a2ca-273e57d622bf">

**Expected behavior**

The line should not be flat.

**Screenshots**

Attached in reproduction.

**Desktop (please complete the following information):**
 - OS: macOS 13.5.1
 - Browser: Chrome 115
 - Version:

**Additional context**

**Comment by AnandChowdhary** [comment]
This is not an error per se I think. It's because there's only 1 item in the chart in the default configuration, but if you for example change the graph CI from once per day to 3 times per day, you'll see the graph with 3 data points. Do you think this makes sense?

**Comment by madhuryadutta** [comment]
Hello @AnandChowdhary ,

I would like to contribute to the documentation of https://upptime.js.org/ about the straight-line Graph issue.

I'm interested in working on this issue Because I have faced the same issue for my status page in the past.

**I think Generating a graph and summary every 6 hours will be a good configuration.**
 I am thinking of writing about it on the "CI schedule" (6 Data point for 24 Hour) and the "Frequently Asked Questions" section. 

Thank you for considering my offer to contribute to the documentation.

Best regards,
Madhurya Dutta

**Comment by AnandChowdhary** [comment]
Sounds good, happy to accept a PR!

**Comment by SukkaW** [comment]
> I would like to contribute to the documentation of https://upptime.js.org/ about the straight-line Graph issue.

That would be awesome!

@AnandChowdhary Maybe we should make this the new default configuration?

**Comment by AnandChowdhary** [comment]
@SukkaW, I made the default once per day in order to not "spam up" the commit history. I think once per day is fine, and maybe we can just not show the graph if we don't have more than 2 data points? I don't think this is necessarily a bug so I'm going to close this issue for now, but if you want to continue the conversation, please feel free to head to the "Discussions" tab and start a new thread there. :)
